site_name: Ilya | Senior DevOps Engineer
site_url: https://GlycineASoya.github.io/portfolio/
theme:
  name: material
  palette:
    scheme: slate

nav:
  - Home: index.md
  - Experience: experience.md
  - Projects & AI: projects.md
  - Homelab & Hardware: hardware.md
  - About Me: about.md