site_name: Ilia | Senior DevOps Engineer
site_url: !ENV [SITE_URL, "http://127.0.0.1:8000/"]

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.tracking

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true